baseURL = "https://grantshandy.github.io/"
languageCode = "en-US"
theme = "friend"

title = "grantsh"
copyright = "&copy; 2023 Grant Handy"

[params]
defaultTheme = "dark"
toc = true
showMenuItems = 3
showReadingTime = true
logo = { logoText = "grantsh" }

[languages.en]
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[[menu.main]]
identifier = "showcase"
name = "Showcase"
url = "/showcase"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
