baseURL = "https://grantshandy.github.io/"
languageCode = "en-us"
theme = "terminal"
pagnate = 5

title = "grantshandy"
subtitle = ""
copyright = "&copy; 2023 Grant Handy"

[params]
themeColor = "red"
autoCover = true
centerTheme = true
showMenuItems = 3
logo = { logoText = "grantshandy" }
favicon = "/profile.jpeg"

[languages.en]
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[[menu.main]]
identifier = "showcase"
name = "Project Showcase"
url = "/showcase"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
