base_url = "https://grantshandy.github.io"
title = "grantsh"
compile_sass = false
build_search_index = false
minify_html = true

[markdown]
highlight_code = true

[extra]
header_pages = [
  { name = "Projects", path = "/projects" },
  { name = "Blog", path = "/posts" },
  { name = "About", path = "/about" }
]