base_url = "https://grantshandy.github.io"
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "1337"

[extra]
links = [
    { name = "Email", url = "mailto://granthandy@pm.me" },
    { name = "Github", url = "https://github.com/grantshandy" },
    { name = "Donate", url = "https://buymeacoffee.com/granthandy" }
]