base_url = "https://grantshandy.github.io"
title = "grantsh"
description = "My Blog"

compile_sass = false
build_search_index = true
minify_html = true

[markdown]
highlight_code = true

[extra]
copyright = "2023 Grant Handy"
menus = [
  { name = "Blog", url = "/blog" },
  { name = "Projects", url = "/projects" }
]