name: "Deploy Site"

on:
  push:
    branches: ["main"]
    
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cachix/install-nix-action@v12

    - name: Build Site
      run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build

    - name: Upload artifacts
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: site
        FOLDER: ./result/site/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
