name: "Deploy Site"

on:
  push:
    branches: ["main"]
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: jakejarvis/hugo-build-action@v0.110.0
      with:
        args: --minify
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './public'
