name: "Deploy Site"

on:
  push:
    branches: ["main"]
    
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Zola Buikd
      uses: crowselectromusic/zola-build@1.2.0

    - name: Upload artifacts
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: site
        FOLDER: ./public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
